### ISSUE TITLE
关于自定义用户名出现 ERR: id: ‘myname’: no such user 问题

### ISSUE THREAD

**Issue by RacleRay** [Codesire-Deng/lazywsl#1]
环境：win10,  wsl2
创建完成系统之后，就只有root用户，这个新建用户是不是有一点问题，大佬有空可以看看么

**Comment by RacleRay** [comment]
额😓，大佬，好像配置文件都是Windows下\r\n换行符，然后执行一直unrecognize \r，才导致安装失败问题。

**Comment by Codesire-Deng** [comment]
> 额😓，大佬，好像配置文件都是Windows下\r\n换行符，然后执行一直unrecognize \r，才导致安装失败问题。

对的，这个问题我遇到过，后来没有复现。我再改一下吧，或者您方便 PR 也可😄

**Comment by RacleRay** [comment]
大佬，我试了试fork改换行符，但是和remote的代码没有差异😂。然后，发现了git有一个设置
`git config --global core.autocrlf  [true | false | input]`
windows下，似乎默认时 true ，clone下来时自动把（LF）转换成（CRLF），才导致这个问题。所以大佬的文件是没问题的。我把设置该为
`git config --global core.autocrlf  false`
直接保留文件本来的符号格式，就没有上面的问题了。
目前问题好像是这个😂，大佬不用花时间改了，我pr也改了个寂寞子牙😁

**Comment by RacleRay** [comment]
大佬，我试了试fork改换行符，但是和remote的代码没有差异😂。然后，发现了git有一个设置
git config --global core.autocrlf  [true | false | input]
windows下，似乎默认时 true ，clone下来时自动把（LF）转换成（CRLF），才导致这个问题。所以大佬的文件是没问题的。我把设置该为
git config --global core.autocrlf  false
直接保留文件本来的符号格式，就没有上面的问题了。
目前问题好像是这个😂，大佬不用花时间改了，我pr也改了个寂寞😁

**Comment by Codesire-Deng** [comment]
现在添加了 [.gitattributes](https://github.com/Codesire-Deng/lazywsl/blob/main/.gitattributes)，应该会保证克隆下来的配置是 LF 换行的了。非常感谢你提出这个问题！

**Comment by RacleRay** [comment]
> 现在添加了 [.gitattributes](https://github.com/Codesire-Deng/lazywsl/blob/main/.gitattributes)，应该会保证克隆下来的配置是 LF 换行的了。非常感谢你提出这个问题！

又学到了，还可以这么改。菜鸟只能做点小事，不值一提😄
